-- Run this ONCE in Render PostgreSQL to seed languages and FAQs
-- First DELETE old languages, then insert new ones

-- Clear existing languages and insert 4 languages
DELETE FROM languages;
INSERT INTO languages (code, name, native_name, greeting, fallback_message, escalation_message, out_of_scope_message, flag_emoji, is_active, display_order) VALUES
('en', 'English', 'English', 'Hello', 'Your information: {data}. Please try again or contact our helpline at 1800-XXX-XXXX.', 'Your issue has been escalated to our specialist team. We will contact you within 24 hours. Ticket ID: {ticketId}', 'I can only help with KYC, transactions, mutual funds, and account-related queries. For other questions, please call our helpline at 1800-XXX-XXXX.', '🇬🇧', true, 1),
('hi', 'Hindi', 'हिंदी', 'नमस्ते', 'आपकी जानकारी: {data}। कृपया दोबारा प्रयास करें या हमारी हेल्पलाइन 1800-XXX-XXXX पर कॉल करें।', 'आपका मुद्दा हमारी विशेषज्ञ टीम को भेज दिया गया है। हम 24 घंटे में आपसे संपर्क करेंगे। Ticket ID: {ticketId}', 'मैं केवल KYC, लेनदेन, म्यूचुअल फंड और खाते से संबंधित प्रश्नों में मदद कर सकता हूं। अन्य सवालों के लिए कृपया हमारी हेल्पलाइन 1800-XXX-XXXX पर कॉल करें।', '🇮🇳', true, 2),
('ta', 'Tamil', 'தமிழ்', 'வணக்கம்', 'உங்கள் தகவல்: {data}. மீண்டும் முயற்சிக்கவும் அல்லது எங்கள் உதவி எண் 1800-XXX-XXXX ஐ தொடர்பு கொள்ளவும்.', 'உங்கள் பிரச்சனை எங்கள் நிபுணர் குழுவிற்கு அனுப்பப்பட்டது. 24 மணி நேரத்தில் தொடர்பு கொள்வோம். Ticket ID: {ticketId}', 'KYC, பரிவர்த்தனைகள், மியூச்சுவல் ஃபண்டுகள் மற்றும் கணக்கு தொடர்பான கேள்விகளுக்கு மட்டுமே உதவ முடியும். மற்ற கேள்விகளுக்கு 1800-XXX-XXXX என்ற எண்ணில் தொடர்பு கொள்ளவும்.', '🇮🇳', true, 3),
('kn', 'Kannada', 'ಕನ್ನಡ', 'ನಮಸ್ಕಾರ', 'ನಿಮ್ಮ ಮಾಹಿತಿ: {data}. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ನಮ್ಮ ಹೆಲ್ಪ್‌ಲೈನ್ 1800-XXX-XXXX ಗೆ ಕರೆ ಮಾಡಿ.', 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ನಮ್ಮ ತಜ್ಞ ತಂಡಕ್ಕೆ ಕಳುಹಿಸಲಾಗಿದೆ. 24 ಗಂಟೆಗಳಲ್ಲಿ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ. Ticket ID: {ticketId}', 'KYC, ವಹಿವಾಟುಗಳು, ಮ್ಯೂಚುವಲ್ ಫಂಡ್‌ಗಳು ಮತ್ತು ಖಾತೆ ಸಂಬಂಧಿತ ಪ್ರಶ್ನೆಗಳಿಗೆ ಮಾತ್ರ ಸಹಾಯ ಮಾಡಬಹುದು. ಇತರ ಪ್ರಶ್ನೆಗಳಿಗೆ 1800-XXX-XXXX ಗೆ ಕರೆ ಮಾಡಿ.', '🇮🇳', true, 4);

-- FAQs Knowledge Base
INSERT INTO faqs (category, question, answer, question_hindi, answer_hindi, question_tamil, answer_tamil, keywords, priority) VALUES
('mutual_fund', 'What is NAV?', 'NAV (Net Asset Value) is the per-unit price of a mutual fund calculated by dividing total assets minus liabilities by outstanding units. NAV changes daily based on market performance.', 'NAV क्या है?', 'NAV म्यूचुअल फंड की प्रति-यूनिट कीमत है। इसकी गणना कुल संपत्ति से देनदारियों को घटाकर, यूनिटों से विभाजित करके की जाती है।', NULL, NULL, 'nav,price,unit,value', 10),
('mutual_fund', 'How to start a SIP?', 'To start SIP: 1) Complete KYC 2) Choose fund based on goals 3) Select amount (min ₹500) 4) Choose date (1-28) 5) Setup auto-debit. SIP invests automatically each month.', 'SIP कैसे शुरू करें?', 'SIP शुरू करने के लिए: 1) KYC पूरा करें 2) फंड चुनें 3) राशि चुनें (न्यूनतम ₹500) 4) तारीख चुनें 5) ऑटो-डेबिट सेट करें।', NULL, NULL, 'sip,start,begin,new,monthly', 10),
('mutual_fund', 'How to redeem mutual fund?', 'To redeem: Go to Portfolio > Select fund > Enter units/amount > Confirm. Amount credited in 1-3 days for equity, T+1 for liquid funds. Exit load may apply within 1 year.', 'म्यूचुअल फंड कैसे रिडीम करें?', 'रिडीम करने के लिए: पोर्टफोलियो में जाएं > फंड चुनें > यूनिट/राशि दर्ज करें > पुष्टि करें। राशि 1-3 दिनों में क्रेडिट होगी।', NULL, NULL, 'redeem,withdraw,sell,exit', 9),
('mutual_fund', 'What is exit load?', 'Exit load is a fee (typically 1%) charged when redeeming before a specified period (usually 1 year for equity). Liquid funds usually have no exit load.', 'एग्जिट लोड क्या है?', 'एग्जिट लोड एक शुल्क है जो निर्दिष्ट अवधि से पहले रिडीम करने पर लगता है। इक्विटी फंड के लिए आमतौर पर 1 साल के भीतर 1%।', NULL, NULL, 'exit,load,fee,charge', 8),
('mutual_fund', 'Can I modify SIP amount?', 'Yes! Go to SIP Management > Select SIP > Modify. Changes take effect from next installment. Minimum amount rules still apply.', 'क्या मैं SIP राशि बदल सकता हूं?', 'हां! SIP प्रबंधन में जाएं > SIP चुनें > संशोधित करें। परिवर्तन अगली किस्त से प्रभावी होंगे।', NULL, NULL, 'sip,modify,change,amount', 9),
('mutual_fund', 'How to stop SIP?', 'To pause: SIP Management > Select > Pause (up to 3 months). To stop: Cancel SIP. No charges for stopping. Existing investments remain in portfolio.', 'SIP कैसे रोकें?', 'रोकने के लिए: SIP प्रबंधन > चुनें > रोकें (3 महीने तक)। बंद करने के लिए: SIP रद्द करें। कोई शुल्क नहीं।', NULL, NULL, 'sip,stop,pause,cancel', 9),
('kyc', 'Documents required for KYC?', 'For KYC: 1) PAN Card (mandatory) 2) Aadhaar for address 3) Passport photo 4) Bank details with cancelled cheque. Video KYC takes 5 minutes online.', 'KYC के लिए कौन से दस्तावेज़?', 'KYC के लिए: 1) पैन कार्ड (अनिवार्य) 2) आधार 3) फोटो 4) बैंक विवरण। वीडियो KYC 5 मिनट में।', NULL, NULL, 'kyc,document,pan,aadhaar', 10),
('kyc', 'Why was KYC rejected?', 'Common rejection reasons: 1) Blurry documents 2) Name mismatch in PAN/Aadhaar 3) Photo mismatch 4) Expired documents. Please resubmit clear documents.', 'KYC क्यों रिजेक्ट हुआ?', 'रिजेक्ट के कारण: 1) धुंधले दस्तावेज़ 2) PAN/आधार में नाम मेल नहीं 3) फोटो मेल नहीं 4) एक्सपायर्ड दस्तावेज़।', NULL, NULL, 'kyc,reject,failed,reason', 9),
('account', 'Why is account blocked?', 'Account blocked due to: 1) Suspicious transactions 2) KYC incomplete/expired 3) Multiple failed logins 4) Regulatory issues. Contact support to unblock.', 'अकाउंट ब्लॉक क्यों है?', 'ब्लॉक के कारण: 1) संदिग्ध लेनदेन 2) KYC अधूरा 3) गलत लॉगिन 4) नियामक मुद्दे। अनब्लॉक के लिए सपोर्ट से संपर्क करें।', NULL, NULL, 'account,block,locked,suspend', 10),
('transaction', 'Why did payment fail?', 'Payment fails due to: 1) Insufficient balance 2) Bank server issues 3) Daily limit exceeded 4) Card expired 5) Wrong credentials. Try again or use different method.', 'पेमेंट फेल क्यों हुआ?', 'फेल के कारण: 1) अपर्याप्त बैलेंस 2) बैंक सर्वर समस्या 3) दैनिक सीमा पार 4) कार्ड एक्सपायर्ड 5) गलत जानकारी।', NULL, NULL, 'payment,fail,failed,error', 10);
